name: Deploy municonnect-be
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t pacifiquerubasha/municonnect-be  .
      - name: Publish Image to docker hub
        run: docker push pacifiquerubasha/municonnect-be:latest
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull pacifiquerubasha/municonnect-be:latest
      - name: Delete old container
        run: docker rm -f municonnect-be-container
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name municonnect-be-container -e MONGO_URI='${{ secrets.MONGO_URI }}' -e FRONTEND_URL='${{ secrets.FRONTEND_URL }}' pacifiquerubasha/municonnect-be